# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  assertions:
  - resource: Microsoft.Windows.Developer/OsVersion
    directives:
      description: Verify min OS version requirement
      allowPrerelease: true
    settings:
      MinVersion: '10.0.22000'
  resources:
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    id: slack
    directives:
      description: Install Slack
      allowPrerelease: true
    settings:
      id: SlackTechnologies.Slack
      source: winget
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    id: outlook
    directives:
      description: Install Outlook for Windows
      allowPrerelease: true
    settings:
      id: 9NRX63209R7B
      source: msstore
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    id: OpenVPN
    directives:
      description: Install OpenVPN
      allowPrerelease: true
    settings:
      id:  OpenVPNTechnologies.OpenVPN
      source: winget
  # TODO jumpcloud
  # TODO envs
