# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  assertions:
  - resource: Microsoft.Windows.Developer/OsVersion
    directives:
      description: Verify min OS version requirement
      allowPrerelease: true
    settings:
      MinVersion: '10.0.22000'
  resources:
  - resource: PSDscResources/WindowsOptionalFeature
    directives:
      description: Enable Hyper-V Feature
    settings :
      Name : Microsoft-Hyper-V
      Ensure: Present
      NoWindowsUpdateCheck: true
  - resource: PSDscResources/WindowsOptionalFeature
    directives:
      description: Enable Virtual Machine platform feature
      # https://pureinfotech.com/hyperv-virtual-machine-platform-windows-hypervisor-platform/
    settings:
      Name : VirtualMachinePlatform
      Ensure: Present
  - resource: PSDscResources/WindowsOptionalFeature
    directives:
      description: Enable WSL feature
    settings:
      Name : Microsoft-Windows-Subsystem-Linux
      Ensure: Present
  - resource: PSDscResources/WindowsOptionalFeature
    directives:
      description: Enable Windows Containers feature
    settings:
      Name : Containers
      Ensure: Present
  - resource: PSDscResources/WindowsOptionalFeature
    directives:
      description: Enable Windows Sandbox feature
    settings:
      Name : Containers-DisposableClientVM
      Ensure: Present
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    id: sysinternals
    directives:
      description: Install MSFT sysinternals
      allowPrerelease: false
    settings:
      id: 9P7KNL5RWT25
      source: msstore      
    # XXX there is no option to specify an install location.
#  - resource: PSDscResources/Script
#    id: sysinternals-tool-folder
#    directives:
#      description: create link to sysinternals
#      allowPrerelease: false
#      dependsOn:
#        - sysinternals
#    settings:
#      GetScript: |
#        $found = Test-Path "c:\tools\procexp.exe"
#        return @{ "Result"= "$found" }
#      SetScript: |
#        $package = Get-AppxPackage -Name 9P7KNL5RWT25
#        New-Item -Path "C:\" -Name "tools" -ItemType directory
#        New-Item -Path "C:\tools\" -Name "procexp.exe" -ItemType SymbolicLink -Value "$($package.InstallLocation}/procexp.exe"
#      TestScript: |
#        return Test-Path "c:\tools\procexp.exe"

