# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
  # todo replace with Microsoft.Windows.Developer
  # https://www.powershellgallery.com/packages/Microsoft.Windows.Developer/0.1.3-alpha/Content/Microsoft.Windows.Developer.psd1
    - resource: PSDscResources/Registry
      directives:
        description: "[explorer] Show file extensions"
      settings:
        Key: "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"
        ValueName: "HideFileExt"
        ValueType: DWord
        ValueData: 0
        Ensure: present
        Force: true
    - resource: PSDscResources/Registry
      directives:
        description: "[explorer] Show hidden files"
      settings:
        Key: "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"
        ValueName: "Hidden"
        ValueType: DWord
        ValueData: 1
        Ensure: present
        Force: true
    - resource: PSDscResources/Registry
      directives:
        description: "[explorer] Show empty drives files"
      settings:
        Key: "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"
        ValueName: "HideDrivesWithNoMedia"
        ValueType: DWord
        ValueData: 0
        Ensure: present
        Force: true
    - resource: PSDscResources/Registry
      directives:
        description: "[explorer] Disable sharing wizard"
      settings:
        Key: "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"
        ValueName: "SharingWizardOn"
        ValueType: DWord
        ValueData: 0
        Ensure: present
        Force: true
    - resource: PSDscResources/Registry
      directives:
        description: "[explorer] Show full path in title"
      settings:
        Key: "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CabinetState"
        ValueName: "FullPath"
        ValueType: DWord
        ValueData: 1
        Ensure: present
        Force: true
