# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
  # todo replace with Microsoft.Windows.Developer
  # https://www.powershellgallery.com/packages/Microsoft.Windows.Developer/0.1.3-alpha/Content/Microsoft.Windows.Developer.psd1
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      directives:
        description: "enable dark mode"
        allowPrerelease: true
      settings:
        Ensure: Present
        RestartExplorer: true # Required to apply changes
    - resource: Microsoft.Windows.Developer/HideFileExtensions
      directives:
        description: "[explorer] Show file extensions"
        allowPrerelease: true
      settings:
        Ensure: Absent
    - resource: Microsoft.Windows.Developer/ShowHiddenFiles
      directives:
        description: "[explorer] Show hidden files"
        allowPrerelease: true
      settings:
        Ensure: Present
    # extra things not exposed (file a PR?)
    - resource: PSDscResources/Registry
      directives:
        description: "[explorer] Show empty drives files"
      settings:
        Key: "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"
        ValueName: "HideDrivesWithNoMedia"
        ValueType: DWord
        ValueData: 0
        Ensure: Present
        Force: true
    - resource: PSDscResources/Registry
      directives:
        description: "[explorer] Disable sharing wizard"
      settings:
        Key: "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"
        ValueName: "SharingWizardOn"
        ValueType: DWord
        ValueData: 0
        Ensure: Present
        Force: true
    - resource: PSDscResources/Registry
      directives:
        description: "[explorer] Show full path in title"
      settings:
        Key: "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CabinetState"
        ValueName: "FullPath"
        ValueType: DWord
        ValueData: 1
        Ensure: Present
        Force: true
    - resource: PSDscResources/Registry
      directives:
        description: "[explorer] Show 'This PC' in desktop"
      settings:
        Key: 'HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel'
        ValueName: '{20D04FE0-3AEA-1069-A2D8-08002B30309D}'
        ValueType: DWord
        ValueData: 0
        Ensure: Present
        Force: true
