# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      directives:
        description: "enable dark mode"
        allowPrerelease: true
      settings:
        Ensure: Present
        RestartExplorer: true # Required to apply changes
    - resource: Microsoft.Windows.Developer/HideFileExtensions
      directives:
        description: "[explorer] Show file extensions"
        allowPrerelease: true
      settings:
        Ensure: Absent
    - resource: Microsoft.Windows.Developer/ShowHiddenFiles
      directives:
        description: "[explorer] Show hidden files"
        allowPrerelease: true
      settings:
        Ensure: Present
    # extra things not exposed (file a PR?)
    - resource: PSDscResources/Registry
      directives:
        description: "[explorer] Show empty drives files"
      settings:
        Key: "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"
        ValueName: "HideDrivesWithNoMedia"
        ValueType: DWord
        ValueData: 0
        Ensure: Present
        Force: true
    - resource: PSDscResources/Registry
      directives:
        description: "[explorer] Disable sharing wizard"
      settings:
        Key: "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"
        ValueName: "SharingWizardOn"
        ValueType: DWord
        ValueData: 0
        Ensure: Present
        Force: true
    - resource: PSDscResources/Registry
      directives:
        description: "[explorer] Show full path in title"
      settings:
        Key: "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CabinetState"
        ValueName: "FullPath"
        ValueType: DWord
        ValueData: 1
        Ensure: Present
        Force: true
    - resource: PSDscResources/Registry
      directives:
        description: "[explorer] Show 'This PC' in desktop"
      settings:
        Key: 'HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel'
        ValueName: '{20D04FE0-3AEA-1069-A2D8-08002B30309D}'
        ValueType: DWord
        ValueData: 0
        Ensure: Present
        Force: true
    ###
    # screen saver
    - resource: PSDscResources/Registry
      directives:
        description: "[screensaver] enable"
      settings:
        Key: 'HKEY_CURRENT_USER\Control Panel\Desktop'
        ValueName: 'ScreenSaveActive'
        ValueType: String
        ValueData: '1'
        Ensure: Present
        Force: true
    - resource: PSDscResources/Registry
      directives:
        description: "[screensaver] require password"
      settings:
        Key: 'HKEY_CURRENT_USER\Control Panel\Desktop'
        ValueName: 'ScreenSaverIsSecure'
        ValueType: String
        ValueData: '1'
        Ensure: Present
        Force: true
    - resource: PSDscResources/Registry
      directives:
        description: "[screensaver] delay"
      settings:
        Key: 'HKEY_CURRENT_USER\Control Panel\Desktop'
        ValueName: 'ScreenSaveTimeOut'
        ValueType: String
        ValueData: '300' # 5 minutes, should be a multiple of 60!
        Ensure: Present
        Force: true
    - resource: PSDscResources/Registry
      directives:
        description: "[screensaver] delay"
      settings:
        Key: 'HKEY_CURRENT_USER\Control Panel\Desktop'
        ValueName: 'SCRNSAVE.EXE'
        ValueType: String
        ValueData: 'C:\Windows\system32\scrnsave.scr' # blank
        Ensure: Present
        Force: true
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      # installed for all users as it is a per user install :-/
      id: notepad2
      directives:
        description: Install Notepad2
        allowPrerelease: true
      settings:
        id: zufuliu.notepad2
