# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  assertions:
  - resource: Microsoft.Windows.Developer/OsVersion
    directives:
      description: Verify min OS version requirement
      allowPrerelease: true
    settings:
      MinVersion: '10.0.22000'
# find and set all tweaks I do here.
# registry keys can be set by e.g. https://github.com/microsoft/winget-cli/discussions/3408#discussioncomment-6387258
# also install any apps.
#  resources:
#  - resource: PSDscResources/WindowsOptionalFeature
#    directives:
#      description: Enable Hyper-V Feature
#    settings :
#      Name : Microsoft-Hyper-V
#      Ensure: Present
#      NoWindowsUpdateCheck: true
#      LogPath: "c:\log.txt"
# apps
  resources:
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    id: spotify
    directives:
      description: Install spotify
      allowPrerelease: true
    settings:
      id: Spotify.Spotify
      source: winget
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    id: clink
    directives:
      description: Install chrisant996/Clink
      allowPrerelease: true
    settings:
      id: chrisant996.Clink
      source: winget
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    id: vscode
    directives:
      description: Install VS Code
      allowPrerelease: true
    settings:
      id: Microsoft.VisualStudioCode
      source: winget
  - resource: Microsoft.WinGet.DSC/WinGetPackage
    id: leafystructure
    directives:
      description: Install Leafy Structures theme
      allowPrerelease: true
    settings:
      id: "9NZPM0HLNWZL"
      source: msstore
      
# config files for clink...
# cygwin?
# gpg
# configure gpg key startup files...
# terminal config?

# settings
